[package]
name = "adventofcode2022"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
ascent = "0.4.0"
derive_more = "0.99.17"
indoc = "1.0"
ndarray = "0.15.6"
regex = "1.7.0"
